DATASET = [
    {
        "service": "Battery Replacement",
        "service_slug": "battery-replacement",
        "location": "Dubai Marina",
        "location_slug": "dubai-marina",
        "intent": "emergency",
        "eta": "30 minutes",
        "warranty": "12-month warranty",
        "cta_phone": "+971-800-227-4878",
        "cta_whatsapp": "https://wa.me/971800CarGuru",
        "price_from": "AED 199",
    },
    {
        "service": "Battery Replacement",
        "service_slug": "battery-replacement",
        "location": "JVC Dubai",
        "location_slug": "jvc-dubai",
        "intent": "same-day",
        "eta": "45 minutes",
        "warranty": "12-month warranty",
        "cta_phone": "+971-800-227-4878",
        "cta_whatsapp": "https://wa.me/971800CarGuru",
        "price_from": "AED 199",
    },
    {
        "service": "Battery Replacement",
        "service_slug": "battery-replacement",
        "location": "Downtown Dubai",
        "location_slug": "downtown-dubai",
        "intent": "24/7",
        "eta": "25 minutes",
        "warranty": "12-month warranty",
        "cta_phone": "+971-800-227-4878",
        "cta_whatsapp": "https://wa.me/971800CarGuru",
        "price_from": "AED 199",
    },
    {
        "service": "Roadside Assistance",
        "service_slug": "roadside-assistance",
        "location": "Abu Dhabi",
        "location_slug": "abu-dhabi",
        "intent": "emergency",
        "eta": "40 minutes",
        "warranty": "Service guarantee",
        "cta_phone": "+971-800-227-4878",
        "cta_whatsapp": "https://wa.me/971800CarGuru",
        "price_from": "AED 149",
    },
    {
        "service": "Towing Service",
        "service_slug": "towing-service",
        "location": "Sharjah",
        "location_slug": "sharjah",
        "intent": "near me",
        "eta": "35 minutes",
        "warranty": "Safe transport guarantee",
        "cta_phone": "+971-800-227-4878",
        "cta_whatsapp": "https://wa.me/971800CarGuru",
        "price_from": "AED 249",
    },
]